export {
  MAX_PLUGIN_FRAME_BYTES,
  PLUGIN_MANIFEST_SCHEMA_VERSION,
  PLUGIN_PROTOCOL_VERSION,
  PluginFrameDecoder,
  encodePluginFrame,
  parsePluginManifest,
  parsePluginMessage,
  pluginCapabilitySchema,
  pluginIntegritySchema,
  pluginManifestSchema,
  pluginMessageSchema,
  pluginOutputSchemaItemSchema,
  pluginPermissionsSchema,
  serializePluginManifest,
  validatePluginManifest,
  type PluginCancelRequest,
  type PluginCapability,
  type Diagnostic,
  type PluginDiagnosticEvent,
  type PluginExecuteRequest,
  type PluginExecuteResponse,
  type PluginHandshakeRequest,
  type PluginHandshakeResponse,
  type PluginIntegrity,
  type PluginManifest,
  type PluginMessage,
  type PluginOutputSchemaItem,
  type PluginPermissions,
  type PluginShutdownRequest,
  type PluginShutdownResponse,
} from "@fuzit/schemas";

export {
  createPlugin,
  type PluginCapabilityContractMap,
  type PluginGraphEnricherInput,
  type PluginGraphEnricherOutput,
  type PluginHandler,
  type PluginImportReference,
  type PluginInstance,
  type PluginParserInput,
  type PluginParserOutput,
  type PluginPolicyInput,
  type PluginPolicyOutput,
  type PluginProfileInput,
  type PluginProfileOutput,
  type PluginRankerInput,
  type PluginRankerOutput,
  type PluginRankerScoreEntry,
  type PluginRendererInput,
  type PluginRendererOutput,
  type PluginSecretDetectorInput,
  type PluginSecretDetectorOutput,
  type PluginSymbolDefinition,
} from "./extension-points.js";

export interface PluginSdkBoundary {
  readonly packageName: "@fuzit/plugin-sdk";
}
